Update to compose release 0.1.0-dev08
zsoltk/compose-router pull request #15
Opened 2020-04-01 22:30 UTC by vanpra

2020-04-02 12:35 UTC, zsoltk commented
@vanpra Thanks for the PR!

I noticed a lot of things are broken visually in both example apps. Can you please compare it to previous version. Most notably text colours make many texts blend in the background in new version (completely invisible), button text colors became black, photo gallery photo full screen disappeared. Please test the apps to make sure they look and behave the same as before.

I'm not sure any of the above is a mistake of migrating text styles, or has anything to do with gradle changes that don't reflect the updates suggested in, but you might want to check: https://developer.android.com/jetpack/androidx/releases/compose

2020-04-02 12:44 UTC, zsoltk requested changes

2020-04-02 12:44 UTC, zsoltk commented on app-lifelike/src/main/java/com/example/lifelike/composable/LoggedIn.kt
> +                                + Modifier.wrapContentSize(Alignment.TopStart)
I believe the suggested new style is chaning the modifiers with fluent API.

2020-04-02 12:44 UTC, zsoltk commented on app-lifelike/src/main/java/com/example/lifelike/composable/LoggedOut.kt
> +import com.example.lifelike.composable.loggedout.*
No star imports please.

2020-04-02 12:44 UTC, zsoltk commented on app-lifelike/src/main/java/com/example/lifelike/composable/LoggedOut.kt
> +                    )
I'd like to keep code formatting in most cases as it was before. I agree with some of the code style modifications, but not all. The PR should ideally introduce changes only in its scope (migrating to dev08).

2020-04-02 12:44 UTC, zsoltk commented on app-lifelike/src/main/java/com/example/lifelike/composable/loggedin/FullScreenPhoto.kt
> +import androidx.ui.layout.*
No star imports please.

2020-04-02 12:44 UTC, zsoltk commented on app-lifelike/src/main/java/com/example/lifelike/composable/loggedin/FullScreenPhoto.kt
> +                        Box(modifier = Modifier.weight(0.8f) + Modifier.fillMaxSize()) {
Let's use fluent api for modifiers here

2020-04-02 12:44 UTC, zsoltk commented on app-lifelike/src/main/java/com/example/lifelike/composable/loggedin/Menu.kt
> +                        modifier = Modifier.fillMaxWidth() + Modifier.padding(8.dp),
Let's use fluent api for modifiers here

2020-04-02 12:44 UTC, zsoltk commented on app-lifelike/src/main/java/com/example/lifelike/composable/loggedin/PhotosOfAlbum.kt
> +import androidx.ui.layout.*
No star imports please.

2020-04-02 12:44 UTC, zsoltk commented on app-lifelike/src/main/java/com/example/lifelike/composable/loggedin/Profile.kt
> +                modifier = Modifier.fillMaxHeight() + Modifier.padding(40.dp),
Let's use fluent api for modifiers here.

2020-04-02 12:44 UTC, zsoltk commented on app-lifelike/src/main/java/com/example/lifelike/composable/loggedout/Splash.kt
> +                            + Modifier.wrapContentSize(Alignment.Center)
Let's use fluent api for modifiers here
```suggestion
                    modifier = Modifier
                            .fillMaxSize()
                            .preferredSizeIn(DpConstraints(maxHeight = 48.dp))
                            .wrapContentSize(Alignment.Center)
```

2020-04-02 12:44 UTC, zsoltk commented on app-lifelike/src/main/java/com/example/lifelike/composable/loggedout/common/RegFlowPanel.kt
> +import androidx.ui.layout.*
No star import please.

2020-04-02 12:44 UTC, zsoltk commented on app-lifelike/src/main/java/com/example/lifelike/composable/loggedout/common/RegFlowPanel.kt
> +                    + Modifier.wrapContentSize(Alignment.CenterEnd)
```suggestion
            modifier = Modifier
                    .fillMaxSize()
                    .preferredSizeIn(DpConstraints(maxHeight = 48.dp))
                    .wrapContentSize(Alignment.CenterEnd)
```

2020-04-02 13:45 UTC, vanpra commented
Thanks for the comments. This should fix most of the stuff you mentioned. I still have to take a look at the layout issues. Looks like the new modifiers have messed a bit with the layout and I'm still investigating the Text colour issue.

2020-04-02 19:42 UTC, vanpra commented
That should be everything fixed now

2020-04-13 02:05 UTC, zsoltk commented
@vanpra Hey, did you actually check it? Both example apps are still broken. Can you please compare against `0.5.2` and have at least the disappearing things back on screen again.

I played around on top of your latest commit and one of the issues seems to be that `Column` and `Row` no longer seem to work with "naked" elements. Once I added `Box`es around everything (as I found in [ColumnSample](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:ui/ui-layout/samples/src/main/java/androidx/ui/layout/samples/ColumnSample.kt;l=39?q=SimpleColumn&ss=androidx%2Fplatform%2Fframeworks%2Fsupport)) it started working again. 

This is needed in all places containing `Column` or `Row`.

Also probably some more button text colors need tweeking in nested containers, but I'd be happy if that was the only issue.

Do you want to fix these?

2020-04-13 11:08 UTC, vanpra commented
@zoltk I've had another look to make sure and the apps look exactly the same except for a slight alignment issue on the logged out screens; everything seems to be visible. Could you please specify the screens which you saw these issues on. I've also had a look at the nested containers app and both apps look identical.

2020-04-13 11:25 UTC, zsoltk commented
@vanpra 

1. `app-nested-containers`: back stack count and local counters are not visible. Only the purple buttons are. On API 28 the padding is 0 for them, while strangely in API 25 that's fine.

2. `app-example`: On API 28 the reg flow panels are collapsed to the top and buttons are not even clickable. Profile page after login is also broken. On API 25 it's looking fine.

The first one is broken regardless of API level. The second example doesn't look exactly your fault since there's API level differences in behaviour. Might be worth asking about it on Slack. 

Nonetheless, if you wrap Composables into `Box` elements instead of putting them directly under `Column` and `Row`, then all the above problematic cases start working correctly.

2020-04-14 10:59 UTC, zsoltk commented
@vanpra Btw created #17 to make your life easier (as well as future Compose version updates). It's up to you which way you want to go now in this PR: you can either fix the issues, or you can make the example apps point to an earlier version, just tell me how you would like to proceed.

2020-04-14 11:13 UTC, vanpra commented
I'm pretty busy at the moment so probably just update the library as I won't get time to fix the issues for a while.

2020-04-14 11:48 UTC, merged