Support for compose 0.1.0-dev16
zsoltk/compose-router pull request #38
Opened 2020-08-10 15:43 UTC by dshatz

Hello, I noticed this library does not work on jetpack-compose dev16 (with errors like `Composable functions can only be used from other Composable functions.`). This is probably because @Composable annotation had been refactored to another package in dev16 and so the compiler cannot match the two different @Composable annotations.

In this MR I have updated the dependency version to `0.1.0-dev16` and adjusted all the imports. It compiles on dev16 and works in my application.

2020-08-10 15:59 UTC, zsoltk commented
Hello @dshatz, thanks for the PR. Can you please make sure the whole project builds fine (see failing GitHub Actions) and checking the example apps they're not broken visually. Cheers.

2020-08-10 16:00 UTC, galex commented
I was looking for this update too, thanks for submitting this PR! 
Let's hope @zsoltk can release a new version quickly 👍

2020-08-10 16:00 UTC, zsoltk requested changes

2020-08-10 16:00 UTC, zsoltk commented on router/src/main/java/com/github/zsoltk/compose/router/Router.kt
> +import androidx.compose.runtime.*
No star imports please.

2020-08-10 16:27 UTC, dshatz commented
Example apps seem to be ok.
I removed the star imports too.
@zsoltik take a look again pls:)

2020-08-10 23:01 UTC, ShikaSD requested changes
Thanks for this update!
It would be nice if you could correct two more small things :)

2020-08-10 23:01 UTC, ShikaSD commented on app-lifelike/src/main/java/com/example/lifelike/composable/loggedin/PhotosOfAlbum.kt
>                          Row {
Seems like it breaks layout of these albums now
Can you add modifier `fillParentMaxWidth` to the `Row` to make it work again? :)

2020-08-10 23:01 UTC, ShikaSD commented on build.gradle
>          kotlin_version = "1.4-M3"
compose works with `1.4.0-rc` version of Kotlin now, so it makes sense to upgrade it as well to avoid inconsistency on the client side.
if you can, please also update `kotlinCompilerVersion` in other build.gradle files to match the version:
```
composeOptions {
        kotlinCompilerVersion "1.4.0-rc"
        kotlinCompilerExtensionVersion compose_version
}
```

2020-08-11 13:24 UTC, zsoltk commented
@dshatz can you please fix the above findings and I'll merge & release right away.

2020-08-11 17:24 UTC, dshatz commented
> @dshatz can you please fix the above findings and I'll merge & release right away.

@zsoltk Should be fine now

2020-08-11 17:58 UTC, zsoltk approved these changes

2020-08-11 17:58 UTC, merged