Updated to support jetpack compose alpha01
zsoltk/compose-router pull request #39
Opened 2020-08-27 08:07 UTC by madhavajay

2020-08-27 08:45 UTC, zsoltk requested changes

2020-08-27 08:45 UTC, zsoltk commented on app-lifelike/src/main/java/com/example/lifelike/composable/loggedout/RegConfirmSmsCode.kt
> +            var code = remember {
This will definitely break this screen, value updates now won't trigger a recompose. I think you need `mutableStateOf`.

2020-08-27 08:45 UTC, zsoltk commented on router/src/main/java/com/github/zsoltk/compose/savedinstancestate/Persistent.kt
>      return state
You broke the functionality here too. Now these are static and cannot cause a recompose on change anymore.

2020-08-28 01:15 UTC, madhavajay commented
@zsoltk Sorry about that, I didn't really understand the API change but iv gone through it now and this looks better.

I have squashed the commits to keep the history clean and prevent confusion by other people looking at the commit history for examples of API change.

Let me know if there are any more issues.

2020-08-28 12:04 UTC, zsoltk approved these changes

2020-08-28 12:04 UTC, merged

2020-08-28 12:04 UTC, zsoltk commented
Thanks @madhavajay